package HealthKnowledgeDAO;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import HealthKnowledgeDAO.HealthKnowledgeType;
import HealthKnowledgeDAO.TCMHealthknowledge;
import HealthKnowledgeDAO.UserKnowledgeMapp;
import HealthKnowledgeDAO.HealthSuggestionsMapp;
import HealthKnowledgeDAO.HealthSuggType;
import HealthKnowledgeDAO.HealthSuggestions;

import HealthKnowledgeDAO.HealthKnowledgeTypeDao;
import HealthKnowledgeDAO.TCMHealthknowledgeDao;
import HealthKnowledgeDAO.UserKnowledgeMappDao;
import HealthKnowledgeDAO.HealthSuggestionsMappDao;
import HealthKnowledgeDAO.HealthSuggTypeDao;
import HealthKnowledgeDAO.HealthSuggestionsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig healthKnowledgeTypeDaoConfig;
    private final DaoConfig tCMHealthknowledgeDaoConfig;
    private final DaoConfig userKnowledgeMappDaoConfig;
    private final DaoConfig healthSuggestionsMappDaoConfig;
    private final DaoConfig healthSuggTypeDaoConfig;
    private final DaoConfig healthSuggestionsDaoConfig;

    private final HealthKnowledgeTypeDao healthKnowledgeTypeDao;
    private final TCMHealthknowledgeDao tCMHealthknowledgeDao;
    private final UserKnowledgeMappDao userKnowledgeMappDao;
    private final HealthSuggestionsMappDao healthSuggestionsMappDao;
    private final HealthSuggTypeDao healthSuggTypeDao;
    private final HealthSuggestionsDao healthSuggestionsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        healthKnowledgeTypeDaoConfig = daoConfigMap.get(HealthKnowledgeTypeDao.class).clone();
        healthKnowledgeTypeDaoConfig.initIdentityScope(type);

        tCMHealthknowledgeDaoConfig = daoConfigMap.get(TCMHealthknowledgeDao.class).clone();
        tCMHealthknowledgeDaoConfig.initIdentityScope(type);

        userKnowledgeMappDaoConfig = daoConfigMap.get(UserKnowledgeMappDao.class).clone();
        userKnowledgeMappDaoConfig.initIdentityScope(type);

        healthSuggestionsMappDaoConfig = daoConfigMap.get(HealthSuggestionsMappDao.class).clone();
        healthSuggestionsMappDaoConfig.initIdentityScope(type);

        healthSuggTypeDaoConfig = daoConfigMap.get(HealthSuggTypeDao.class).clone();
        healthSuggTypeDaoConfig.initIdentityScope(type);

        healthSuggestionsDaoConfig = daoConfigMap.get(HealthSuggestionsDao.class).clone();
        healthSuggestionsDaoConfig.initIdentityScope(type);

        healthKnowledgeTypeDao = new HealthKnowledgeTypeDao(healthKnowledgeTypeDaoConfig, this);
        tCMHealthknowledgeDao = new TCMHealthknowledgeDao(tCMHealthknowledgeDaoConfig, this);
        userKnowledgeMappDao = new UserKnowledgeMappDao(userKnowledgeMappDaoConfig, this);
        healthSuggestionsMappDao = new HealthSuggestionsMappDao(healthSuggestionsMappDaoConfig, this);
        healthSuggTypeDao = new HealthSuggTypeDao(healthSuggTypeDaoConfig, this);
        healthSuggestionsDao = new HealthSuggestionsDao(healthSuggestionsDaoConfig, this);

        registerDao(HealthKnowledgeType.class, healthKnowledgeTypeDao);
        registerDao(TCMHealthknowledge.class, tCMHealthknowledgeDao);
        registerDao(UserKnowledgeMapp.class, userKnowledgeMappDao);
        registerDao(HealthSuggestionsMapp.class, healthSuggestionsMappDao);
        registerDao(HealthSuggType.class, healthSuggTypeDao);
        registerDao(HealthSuggestions.class, healthSuggestionsDao);
    }
    
    public void clear() {
        healthKnowledgeTypeDaoConfig.getIdentityScope().clear();
        tCMHealthknowledgeDaoConfig.getIdentityScope().clear();
        userKnowledgeMappDaoConfig.getIdentityScope().clear();
        healthSuggestionsMappDaoConfig.getIdentityScope().clear();
        healthSuggTypeDaoConfig.getIdentityScope().clear();
        healthSuggestionsDaoConfig.getIdentityScope().clear();
    }

    public HealthKnowledgeTypeDao getHealthKnowledgeTypeDao() {
        return healthKnowledgeTypeDao;
    }

    public TCMHealthknowledgeDao getTCMHealthknowledgeDao() {
        return tCMHealthknowledgeDao;
    }

    public UserKnowledgeMappDao getUserKnowledgeMappDao() {
        return userKnowledgeMappDao;
    }

    public HealthSuggestionsMappDao getHealthSuggestionsMappDao() {
        return healthSuggestionsMappDao;
    }

    public HealthSuggTypeDao getHealthSuggTypeDao() {
        return healthSuggTypeDao;
    }

    public HealthSuggestionsDao getHealthSuggestionsDao() {
        return healthSuggestionsDao;
    }

}
