package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HEALTH_KNOWLEDGE_TYPE.
 */
public class HealthKnowledgeType {

    private Long id;
    private Integer healthknowltypeid;
    private String healthknowltypename;
    private String classifyexplain;
    private Integer healthknowltypecode;
    private String healthknowltypereamrks;

    public HealthKnowledgeType() {
    }

    public HealthKnowledgeType(Long id) {
        this.id = id;
    }

    public HealthKnowledgeType(Long id, Integer healthknowltypeid, String healthknowltypename, String classifyexplain, Integer healthknowltypecode, String healthknowltypereamrks) {
        this.id = id;
        this.healthknowltypeid = healthknowltypeid;
        this.healthknowltypename = healthknowltypename;
        this.classifyexplain = classifyexplain;
        this.healthknowltypecode = healthknowltypecode;
        this.healthknowltypereamrks = healthknowltypereamrks;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getHealthknowltypeid() {
        return healthknowltypeid;
    }

    public void setHealthknowltypeid(Integer healthknowltypeid) {
        this.healthknowltypeid = healthknowltypeid;
    }

    public String getHealthknowltypename() {
        return healthknowltypename;
    }

    public void setHealthknowltypename(String healthknowltypename) {
        this.healthknowltypename = healthknowltypename;
    }

    public String getClassifyexplain() {
        return classifyexplain;
    }

    public void setClassifyexplain(String classifyexplain) {
        this.classifyexplain = classifyexplain;
    }

    public Integer getHealthknowltypecode() {
        return healthknowltypecode;
    }

    public void setHealthknowltypecode(Integer healthknowltypecode) {
        this.healthknowltypecode = healthknowltypecode;
    }

    public String getHealthknowltypereamrks() {
        return healthknowltypereamrks;
    }

    public void setHealthknowltypereamrks(String healthknowltypereamrks) {
        this.healthknowltypereamrks = healthknowltypereamrks;
    }

}
