package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TCMHEALTHKNOWLEDGE.
 */
public class TCMHealthknowledge {

    private Long id;
    private Integer healthknowledgeid;
    private String healthknowledgetitle;
    private String healthknowledgecontent;
    private java.util.Date exersuggtime;
    private Integer healthknowledgecode;
    private Integer temp_healthknowltypeid;
    private String healthknowledgeremarks;
    private Integer healthknowledgeflag;

    public TCMHealthknowledge() {
    }

    public TCMHealthknowledge(Long id) {
        this.id = id;
    }

    public TCMHealthknowledge(Long id, Integer healthknowledgeid, String healthknowledgetitle, String healthknowledgecontent, java.util.Date exersuggtime, Integer healthknowledgecode, Integer temp_healthknowltypeid, String healthknowledgeremarks, Integer healthknowledgeflag) {
        this.id = id;
        this.healthknowledgeid = healthknowledgeid;
        this.healthknowledgetitle = healthknowledgetitle;
        this.healthknowledgecontent = healthknowledgecontent;
        this.exersuggtime = exersuggtime;
        this.healthknowledgecode = healthknowledgecode;
        this.temp_healthknowltypeid = temp_healthknowltypeid;
        this.healthknowledgeremarks = healthknowledgeremarks;
        this.healthknowledgeflag = healthknowledgeflag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getHealthknowledgeid() {
        return healthknowledgeid;
    }

    public void setHealthknowledgeid(Integer healthknowledgeid) {
        this.healthknowledgeid = healthknowledgeid;
    }

    public String getHealthknowledgetitle() {
        return healthknowledgetitle;
    }

    public void setHealthknowledgetitle(String healthknowledgetitle) {
        this.healthknowledgetitle = healthknowledgetitle;
    }

    public String getHealthknowledgecontent() {
        return healthknowledgecontent;
    }

    public void setHealthknowledgecontent(String healthknowledgecontent) {
        this.healthknowledgecontent = healthknowledgecontent;
    }

    public java.util.Date getExersuggtime() {
        return exersuggtime;
    }

    public void setExersuggtime(java.util.Date exersuggtime) {
        this.exersuggtime = exersuggtime;
    }

    public Integer getHealthknowledgecode() {
        return healthknowledgecode;
    }

    public void setHealthknowledgecode(Integer healthknowledgecode) {
        this.healthknowledgecode = healthknowledgecode;
    }

    public Integer getTemp_healthknowltypeid() {
        return temp_healthknowltypeid;
    }

    public void setTemp_healthknowltypeid(Integer temp_healthknowltypeid) {
        this.temp_healthknowltypeid = temp_healthknowltypeid;
    }

    public String getHealthknowledgeremarks() {
        return healthknowledgeremarks;
    }

    public void setHealthknowledgeremarks(String healthknowledgeremarks) {
        this.healthknowledgeremarks = healthknowledgeremarks;
    }

    public Integer getHealthknowledgeflag() {
        return healthknowledgeflag;
    }

    public void setHealthknowledgeflag(Integer healthknowledgeflag) {
        this.healthknowledgeflag = healthknowledgeflag;
    }

}
