package UserHealthKnowageDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import UserHealthKnowageDao.UserHealthknowage;

import UserHealthKnowageDao.UserHealthknowageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userHealthknowageDaoConfig;

    private final UserHealthknowageDao userHealthknowageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userHealthknowageDaoConfig = daoConfigMap.get(UserHealthknowageDao.class).clone();
        userHealthknowageDaoConfig.initIdentityScope(type);

        userHealthknowageDao = new UserHealthknowageDao(userHealthknowageDaoConfig, this);

        registerDao(UserHealthknowage.class, userHealthknowageDao);
    }
    
    public void clear() {
        userHealthknowageDaoConfig.getIdentityScope().clear();
    }

    public UserHealthknowageDao getUserHealthknowageDao() {
        return userHealthknowageDao;
    }

}
