package PhysiqueConsIdentyDAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_HEALTHKNOWAGE.
 */
public class UserHealthknowage {

    private Long id;
    private Integer userknowledgemappid;
    private Double temp_picturelistid;
    private Double healthknowledgetime;
    private Double userid;
    private Double username;
    private String healthknowltypeid;
    private String healthknowltypename;
    private String healthknowledgetitle;
    private String healthknowledgecontent;
    private String healthknowledgecode;

    public UserHealthknowage() {
    }

    public UserHealthknowage(Long id) {
        this.id = id;
    }

    public UserHealthknowage(Long id, Integer userknowledgemappid, Double temp_picturelistid, Double healthknowledgetime, Double userid, Double username, String healthknowltypeid, String healthknowltypename, String healthknowledgetitle, String healthknowledgecontent, String healthknowledgecode) {
        this.id = id;
        this.userknowledgemappid = userknowledgemappid;
        this.temp_picturelistid = temp_picturelistid;
        this.healthknowledgetime = healthknowledgetime;
        this.userid = userid;
        this.username = username;
        this.healthknowltypeid = healthknowltypeid;
        this.healthknowltypename = healthknowltypename;
        this.healthknowledgetitle = healthknowledgetitle;
        this.healthknowledgecontent = healthknowledgecontent;
        this.healthknowledgecode = healthknowledgecode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserknowledgemappid() {
        return userknowledgemappid;
    }

    public void setUserknowledgemappid(Integer userknowledgemappid) {
        this.userknowledgemappid = userknowledgemappid;
    }

    public Double getTemp_picturelistid() {
        return temp_picturelistid;
    }

    public void setTemp_picturelistid(Double temp_picturelistid) {
        this.temp_picturelistid = temp_picturelistid;
    }

    public Double getHealthknowledgetime() {
        return healthknowledgetime;
    }

    public void setHealthknowledgetime(Double healthknowledgetime) {
        this.healthknowledgetime = healthknowledgetime;
    }

    public Double getUserid() {
        return userid;
    }

    public void setUserid(Double userid) {
        this.userid = userid;
    }

    public Double getUsername() {
        return username;
    }

    public void setUsername(Double username) {
        this.username = username;
    }

    public String getHealthknowltypeid() {
        return healthknowltypeid;
    }

    public void setHealthknowltypeid(String healthknowltypeid) {
        this.healthknowltypeid = healthknowltypeid;
    }

    public String getHealthknowltypename() {
        return healthknowltypename;
    }

    public void setHealthknowltypename(String healthknowltypename) {
        this.healthknowltypename = healthknowltypename;
    }

    public String getHealthknowledgetitle() {
        return healthknowledgetitle;
    }

    public void setHealthknowledgetitle(String healthknowledgetitle) {
        this.healthknowledgetitle = healthknowledgetitle;
    }

    public String getHealthknowledgecontent() {
        return healthknowledgecontent;
    }

    public void setHealthknowledgecontent(String healthknowledgecontent) {
        this.healthknowledgecontent = healthknowledgecontent;
    }

    public String getHealthknowledgecode() {
        return healthknowledgecode;
    }

    public void setHealthknowledgecode(String healthknowledgecode) {
        this.healthknowledgecode = healthknowledgecode;
    }

}
