package HealthSuggestionCombileSimplifyDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import HealthSuggestionCombileSimplifyDao.HealthSuggestionCombileSimplify;

import HealthSuggestionCombileSimplifyDao.HealthSuggestionCombileSimplifyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig healthSuggestionCombileSimplifyDaoConfig;

    private final HealthSuggestionCombileSimplifyDao healthSuggestionCombileSimplifyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        healthSuggestionCombileSimplifyDaoConfig = daoConfigMap.get(HealthSuggestionCombileSimplifyDao.class).clone();
        healthSuggestionCombileSimplifyDaoConfig.initIdentityScope(type);

        healthSuggestionCombileSimplifyDao = new HealthSuggestionCombileSimplifyDao(healthSuggestionCombileSimplifyDaoConfig, this);

        registerDao(HealthSuggestionCombileSimplify.class, healthSuggestionCombileSimplifyDao);
    }
    
    public void clear() {
        healthSuggestionCombileSimplifyDaoConfig.getIdentityScope().clear();
    }

    public HealthSuggestionCombileSimplifyDao getHealthSuggestionCombileSimplifyDao() {
        return healthSuggestionCombileSimplifyDao;
    }

}
