package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AVERAGE_AMOUNT_STD.
 */
public class AverageAmountStd {

    private Long id;
    private Integer amountnumofdays;
    private String averageamountremarks;
    private java.util.Date amountstoptime;

    public AverageAmountStd() {
    }

    public AverageAmountStd(Long id) {
        this.id = id;
    }

    public AverageAmountStd(Long id, Integer amountnumofdays, String averageamountremarks, java.util.Date amountstoptime) {
        this.id = id;
        this.amountnumofdays = amountnumofdays;
        this.averageamountremarks = averageamountremarks;
        this.amountstoptime = amountstoptime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAmountnumofdays() {
        return amountnumofdays;
    }

    public void setAmountnumofdays(Integer amountnumofdays) {
        this.amountnumofdays = amountnumofdays;
    }

    public String getAverageamountremarks() {
        return averageamountremarks;
    }

    public void setAverageamountremarks(String averageamountremarks) {
        this.averageamountremarks = averageamountremarks;
    }

    public java.util.Date getAmountstoptime() {
        return amountstoptime;
    }

    public void setAmountstoptime(java.util.Date amountstoptime) {
        this.amountstoptime = amountstoptime;
    }

}
