package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONSITITUTE_IDENTIFY_RESULT.
 */
public class ConsitituteIdentifyResult {

    private Long id;
    private Integer identifyresultid;
    private String temp_userid;
    private Integer temp_physiqueinfoid;
    private String  constituteidentifytime;
    private String constituteidentifyremarks;
    private String constituteidentifyresult;
    private Integer constituteldentifyflag;


    public ConsitituteIdentifyResult() {
    }

    public ConsitituteIdentifyResult(Long id) {
        this.id = id;
    }
    public ConsitituteIdentifyResult(Long id,Integer identifyresultid,String temp_userid, Integer temp_physiqueinfoid, String constituteidentifytime, String constituteidentifyremarks, String constituteidentifyresult,Integer constituteldentifyflag) {
        this.id=id;
        this.identifyresultid = identifyresultid;
        this.temp_userid = temp_userid;
        this.temp_physiqueinfoid = temp_physiqueinfoid;
        this.constituteidentifytime = constituteidentifytime;
        this.constituteidentifyremarks = constituteidentifyremarks;
        this.constituteidentifyresult = constituteidentifyresult;
        this.constituteldentifyflag = constituteldentifyflag;
    }

    public ConsitituteIdentifyResult(String temp_userid, Integer temp_physiqueinfoid, String constituteidentifytime, String constituteidentifyremarks, String constituteidentifyresult,Integer constituteldentifyflag) {

        this.temp_userid = temp_userid;
        this.temp_physiqueinfoid = temp_physiqueinfoid;
        this.constituteidentifytime = constituteidentifytime;
        this.constituteidentifyremarks = constituteidentifyremarks;
        this.constituteidentifyresult = constituteidentifyresult;
        this.constituteldentifyflag = constituteldentifyflag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdentifyresultid() {
        return identifyresultid;
    }

    public void setIdentifyresultid(Integer identifyresultid) {
        this.identifyresultid = identifyresultid;
    }

    public String getTemp_userid() {
        return temp_userid;
    }

    public void setTemp_userid(String temp_userid) {
        this.temp_userid = temp_userid;
    }

    public Integer getTemp_physiqueinfoid() {
        return temp_physiqueinfoid;
    }

    public void setTemp_physiqueinfoid(Integer temp_physiqueinfoid) {
        this.temp_physiqueinfoid = temp_physiqueinfoid;
    }

    public String getConstituteidentifytime() {
        return constituteidentifytime;
    }

    public void setConstituteidentifytime(String constituteidentifytime) {
        this.constituteidentifytime = constituteidentifytime;
    }

    public String getConstituteidentifyremarks() {
        return constituteidentifyremarks;
    }

    public void setConstituteidentifyremarks(String constituteidentifyremarks) {
        this.constituteidentifyremarks = constituteidentifyremarks;
    }

    public String getConstituteidentifyresult() {
        return constituteidentifyresult;
    }

    public void setConstituteidentifyresult(String constituteidentifyresult) {
        this.constituteidentifyresult = constituteidentifyresult;
    }
    public Integer getConstituteldentifyflag(){return constituteldentifyflag;}
    public void  setConstituteldentifyflag(Integer constituteldentifyflag){
        this.constituteldentifyflag = constituteldentifyflag;
    }
}
