package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIETARY_RECORDS.
 */
public class DietaryRecords {

    private Long id;
    private Integer eatingrecordid;
    private String foodtypename;
    private String foodname ;
    private Double eatingamount;
    private String unitname;
    private String eatingtime;
    private String eatingrecordsuptime;
    private String eatinginforemarks;
    private String temp_userid;
    private String eatingstateback;
    private Integer temp_foodnutritionid;
    private Integer temp_locationinfoid;
    private Integer temp_intelligentdeviceid;
    private Integer intelligentdevicecode;
    private Integer eatingupflag;
    private Integer setmealcode;
    private String eatingovertime;
    public DietaryRecords() {
    }


    public DietaryRecords(Long id) {
        this.id = id;
    }

    public DietaryRecords(Long id, Integer eatingrecordid, String foodtypename, String foodname , Double eatingamount, String unitname, String eatingtime, String eatingrecordsuptime, String eatinginforemarks, String temp_userid, String eatingstateback, Integer temp_foodnutritionid, Integer temp_locationinfoid, Integer temp_intelligentdeviceid, Integer intelligentdevicecode, Integer eatingupflag, Integer setmealcode,String eatingovertime) {
        this.id = id;
        this.eatingrecordid = eatingrecordid;
        this.foodtypename = foodtypename;
        this.foodname  = foodname ;
        this.eatingamount = eatingamount;
        this.unitname = unitname;
        this.eatingtime = eatingtime;
        this.eatingrecordsuptime = eatingrecordsuptime;
        this.eatinginforemarks = eatinginforemarks;
        this.temp_userid = temp_userid;
        this.eatingstateback = eatingstateback;
        this.temp_foodnutritionid = temp_foodnutritionid;
        this.temp_locationinfoid = temp_locationinfoid;
        this.temp_intelligentdeviceid = temp_intelligentdeviceid;
        this.intelligentdevicecode = intelligentdevicecode;
        this.eatingupflag = eatingupflag;
        this.setmealcode = setmealcode;
        this.eatingovertime = eatingovertime;
    }
    public DietaryRecords( String foodtypename, String foodname , String unitname, String eatingtime, String eatingovertime, String eatingrecordsuptime, String eatinginforemarks, String temp_userid, Integer temp_foodnutritionid, Integer eatingupflag) {

        this.foodtypename = foodtypename;
        this.foodname  = foodname ;
        this.unitname = unitname;
        this.eatingtime = eatingtime;
        this.eatingovertime = eatingovertime;
        this.eatingrecordsuptime = eatingrecordsuptime;
        this.eatinginforemarks = eatinginforemarks;
        this.temp_userid = temp_userid;
        this.temp_foodnutritionid = temp_foodnutritionid;
        this.eatingupflag = eatingupflag;

    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getEatingrecordid() {
        return eatingrecordid;
    }

    public void setEatingrecordid(Integer eatingrecordid) {
        this.eatingrecordid = eatingrecordid;
    }

    public String getFoodtypename() {
        return foodtypename;
    }

    public void setFoodtypename(String foodtypename) {
        this.foodtypename = foodtypename;
    }

    public String getFoodname () {
        return foodname ;
    }

    public void setFoodname (String foodname ) {
        this.foodname  = foodname ;
    }

    public Double getEatingamount() {
        return eatingamount;
    }

    public void setEatingamount(Double eatingamount) {
        this.eatingamount = eatingamount;
    }

    public String getUnitname() {
        return unitname;
    }

    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }

    public String getEatingtime() {
        return eatingtime;
    }

    public void setEatingtime(String eatingtime) {
        this.eatingtime = eatingtime;
    }

    public String getEatingrecordsuptime() {
        return eatingrecordsuptime;
    }

    public void setEatingrecordsuptime(String eatingrecordsuptime) {
        this.eatingrecordsuptime = eatingrecordsuptime;
    }

    public String getEatinginforemarks() {
        return eatinginforemarks;
    }

    public void setEatinginforemarks(String eatinginforemarks) {
        this.eatinginforemarks = eatinginforemarks;
    }

    public String getTemp_userid() {
        return temp_userid;
    }

    public void setTemp_userid(String temp_userid) {
        this.temp_userid = temp_userid;
    }

    public String getEatingstateback() {
        return eatingstateback;
    }

    public void setEatingstateback(String eatingstateback) {
        this.eatingstateback = eatingstateback;
    }

    public Integer getTemp_foodnutritionid() {
        return temp_foodnutritionid;
    }

    public void setTemp_foodnutritionid(Integer temp_foodnutritionid) {
        this.temp_foodnutritionid = temp_foodnutritionid;
    }

    public Integer getTemp_locationinfoid() {
        return temp_locationinfoid;
    }

    public void setTemp_locationinfoid(Integer temp_locationinfoid) {
        this.temp_locationinfoid = temp_locationinfoid;
    }

    public Integer getTemp_intelligentdeviceid() {
        return temp_intelligentdeviceid;
    }

    public void setTemp_intelligentdeviceid(Integer temp_intelligentdeviceid) {
        this.temp_intelligentdeviceid = temp_intelligentdeviceid;
    }

    public Integer getIntelligentdevicecode() {
        return intelligentdevicecode;
    }

    public void setIntelligentdevicecode(Integer intelligentdevicecode) {
        this.intelligentdevicecode = intelligentdevicecode;
    }

    public Integer getEatingupflag() {
        return eatingupflag;
    }

    public void setEatingupflag(Integer eatingupflag) {
        this.eatingupflag = eatingupflag;
    }

    public Integer getSetmealcode() {
        return setmealcode;
    }

    public void setSetmealcode(Integer setmealcode) {
        this.setmealcode = setmealcode;
    }

    public String getEatingovertime() {
        return eatingovertime;
    }

    public void setEatingovertime(String eatingovertime) {
        this.eatingovertime = eatingovertime;
    }
}
