package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EATING_PREFER_RECORDS.
 */
public class EatingPreferRecords {

    private Long id;
    private Integer eatingpreferid;
    private String foodtypename;
    private String foodname;
    private Double preference;
    private Double averageintake;
    private Integer temp_foodnutritionid;
    private String temp_userid;
    private String eatingoftenstarttime;
    private String eatingoftenovertime;
    private Integer temp_locationinfoid;
    private String additemtime;
    private Integer currentlypreferflag;
    public EatingPreferRecords() {
    }

    public EatingPreferRecords(Long id) {
        this.id = id;
    }

    public EatingPreferRecords(Long id, Integer eatingpreferid, String foodtypename, String foodname, Double preference, Double averageintake, Integer temp_foodnutritionid, String temp_userid, String eatingoftenstarttime, String eatingoftenovertime, Integer temp_locationinfoid, String additemtime, Integer currentlypreferflag) {
        this.id = id;
        this.eatingpreferid = eatingpreferid;
        this.foodtypename = foodtypename;
        this.foodname = foodname;
        this.preference = preference;
        this.averageintake = averageintake;
        this.temp_foodnutritionid = temp_foodnutritionid;
        this.temp_userid = temp_userid;
        this.eatingoftenstarttime = eatingoftenstarttime;
        this.eatingoftenovertime = eatingoftenovertime;
        this.temp_locationinfoid = temp_locationinfoid;
        this.additemtime = additemtime;
        this.currentlypreferflag = currentlypreferflag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getEatingpreferid() {
        return eatingpreferid;
    }

    public void setEatingpreferid(Integer eatingpreferid) {
        this.eatingpreferid = eatingpreferid;
    }

    public String getFoodtypename() {
        return foodtypename;
    }

    public void setFoodtypename(String foodtypename) {
        this.foodtypename = foodtypename;
    }

    public String getFoodname() {
        return foodname;
    }

    public void setFoodname(String foodname) {
        this.foodname = foodname;
    }

    public Double getPreference() {
        return preference;
    }

    public void setPreference(Double preference) {
        this.preference = preference;
    }

    public Double getAverageintake() {
        return averageintake;
    }

    public void setAverageintake(Double averageintake) {
        this.averageintake = averageintake;
    }

    public Integer getTemp_foodnutritionid() {
        return temp_foodnutritionid;
    }

    public void setTemp_foodnutritionid(Integer temp_foodnutritionid) {
        this.temp_foodnutritionid = temp_foodnutritionid;
    }

    public String getTemp_userid() {
        return temp_userid;
    }

    public void setTemp_userid(String temp_userid) {
        this.temp_userid = temp_userid;
    }

    public String getEatingoftenstarttime() {
        return eatingoftenstarttime;
    }

    public void setEatingoftenstarttime(String eatingoftenstarttime) {
        this.eatingoftenstarttime = eatingoftenstarttime;
    }

    public String getEatingoftenovertime() {
        return eatingoftenovertime;
    }

    public void setEatingoftenovertime(String eatingoftenovertime) {
        this.eatingoftenovertime = eatingoftenovertime;
    }

    public Integer getTemp_locationinfoid() {
        return temp_locationinfoid;
    }

    public void setTemp_locationinfoid(Integer temp_locationinfoid) {
        this.temp_locationinfoid = temp_locationinfoid;
    }

    public String getAdditemtime() {
        return additemtime;
    }

    public void setAdditemtime(String additemtime) {
        this.additemtime = additemtime;
    }

    public Integer getCurrentlypreferflag() {
        return currentlypreferflag;
    }

    public void setCurrentlypreferflag(Integer currentlypreferflag) {
        this.currentlypreferflag = currentlypreferflag;
    }
}
