package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EATING_ANALYSIS.
 */
public class EatingAnalysis {

    private Long id;
    private Double energyintake;
    private String energyunit;
    private Double moistureintake;
    private String moistureunit;
    private Double proteinintake;
    private String proteinunit;
    private Double fatintake;
    private String fatunit;
    private Double fiberintake;
    private String fiberunit;
    private Double carbohydrateintake;
    private String carbohydrateunit;
    private Double vitaminaintake;
    private String vitaminaunit;
    private Double vitaminb1intake;
    private String vitaminb1unit;
    private Double vitaminb2intake;
    private String vitaminb2unit;
    private Double vitaminb6intake;
    private String vitaminb6unit;
    private Double vitaminb12intake;
    private String vitaminb12unit;
    private Double vitamincintake;
    private String vitamincunit;
    private Double vitamindintake;
    private String vitamindunit;
    private Double vitamineintake;
    private String vitaminunit;
    private Double vitaminkintake;
    private String vitaminkunit;
    private Double nicotinicacidintake;
    private String nicotinicunit;
    private Double folateintake;
    private String folateunit;
    private Double sodiumintake;
    private String sodiumunit;
    private Double calciumintake;
    private String calciumunit;
    private Double ironintake;
    private String ironunit;
    private Double potassiumintake;
    private String potassiumunit;
    private Double zincintake;
    private String zincunit;
    private Double magnesiumintake;
    private String magnesiumunit;
    private Double copperintake;
    private String copperunit;
    private Double chomuimintake;
    private String chomuimunit;
    private Double mangaesiumintake;
    private String mangaesiumunit;
    private Double molybdenumintake;
    private String molybdenumunit;
    private Double iodineintake;
    private String iodineunit;
    private Double phosphrusintake;
    private String phosphrusunit;
    private Double seleniumintake;
    private String seleniumunit;
    private Double fluorineintake;
    private String fluorineunit;
    private Double cholesterolintake;
    private String cholesterolunit;
    private Double saturatedintake;
    private String saturatedunit;
    private Double acidregurgitationintake;
    private String acidregurgitationunit;
    private Double biotinintake;
    private String biotinunit;
    private Double cholineintake;
    private String cholineunit;
    private Integer temp_eatingrecordid;

    public EatingAnalysis() {
    }

    public EatingAnalysis(Long id) {
        this.id = id;
    }

    public EatingAnalysis(Long id, Double energyintake, String energyunit, Double moistureintake, String moistureunit, Double proteinintake, String proteinunit, Double fatintake, String fatunit, Double fiberintake, String fiberunit, Double carbohydrateintake, String carbohydrateunit, Double vitaminaintake, String vitaminaunit, Double vitaminb1intake, String vitaminb1unit, Double vitaminb2intake, String vitaminb2unit, Double vitaminb6intake, String vitaminb6unit, Double vitaminb12intake, String vitaminb12unit, Double vitamincintake, String vitamincunit, Double vitamindintake, String vitamindunit, Double vitamineintake, String vitaminunit, Double vitaminkintake, String vitaminkunit, Double nicotinicacidintake, String nicotinicunit, Double folateintake, String folateunit, Double sodiumintake, String sodiumunit, Double calciumintake, String calciumunit, Double ironintake, String ironunit, Double potassiumintake, String potassiumunit, Double zincintake, String zincunit, Double magnesiumintake, String magnesiumunit, Double copperintake, String copperunit, Double chomuimintake, String chomuimunit, Double mangaesiumintake, String mangaesiumunit, Double molybdenumintake, String molybdenumunit, Double iodineintake, String iodineunit, Double phosphrusintake, String phosphrusunit, Double seleniumintake, String seleniumunit, Double fluorineintake, String fluorineunit, Double cholesterolintake, String cholesterolunit, Double saturatedintake, String saturatedunit, Double acidregurgitationintake, String acidregurgitationunit, Double biotinintake, String biotinunit, Double cholineintake, String cholineunit, Integer temp_eatingrecordid) {
        this.id = id;
        this.energyintake = energyintake;
        this.energyunit = energyunit;
        this.moistureintake = moistureintake;
        this.moistureunit = moistureunit;
        this.proteinintake = proteinintake;
        this.proteinunit = proteinunit;
        this.fatintake = fatintake;
        this.fatunit = fatunit;
        this.fiberintake = fiberintake;
        this.fiberunit = fiberunit;
        this.carbohydrateintake = carbohydrateintake;
        this.carbohydrateunit = carbohydrateunit;
        this.vitaminaintake = vitaminaintake;
        this.vitaminaunit = vitaminaunit;
        this.vitaminb1intake = vitaminb1intake;
        this.vitaminb1unit = vitaminb1unit;
        this.vitaminb2intake = vitaminb2intake;
        this.vitaminb2unit = vitaminb2unit;
        this.vitaminb6intake = vitaminb6intake;
        this.vitaminb6unit = vitaminb6unit;
        this.vitaminb12intake = vitaminb12intake;
        this.vitaminb12unit = vitaminb12unit;
        this.vitamincintake = vitamincintake;
        this.vitamincunit = vitamincunit;
        this.vitamindintake = vitamindintake;
        this.vitamindunit = vitamindunit;
        this.vitamineintake = vitamineintake;
        this.vitaminunit = vitaminunit;
        this.vitaminkintake = vitaminkintake;
        this.vitaminkunit = vitaminkunit;
        this.nicotinicacidintake = nicotinicacidintake;
        this.nicotinicunit = nicotinicunit;
        this.folateintake = folateintake;
        this.folateunit = folateunit;
        this.sodiumintake = sodiumintake;
        this.sodiumunit = sodiumunit;
        this.calciumintake = calciumintake;
        this.calciumunit = calciumunit;
        this.ironintake = ironintake;
        this.ironunit = ironunit;
        this.potassiumintake = potassiumintake;
        this.potassiumunit = potassiumunit;
        this.zincintake = zincintake;
        this.zincunit = zincunit;
        this.magnesiumintake = magnesiumintake;
        this.magnesiumunit = magnesiumunit;
        this.copperintake = copperintake;
        this.copperunit = copperunit;
        this.chomuimintake = chomuimintake;
        this.chomuimunit = chomuimunit;
        this.mangaesiumintake = mangaesiumintake;
        this.mangaesiumunit = mangaesiumunit;
        this.molybdenumintake = molybdenumintake;
        this.molybdenumunit = molybdenumunit;
        this.iodineintake = iodineintake;
        this.iodineunit = iodineunit;
        this.phosphrusintake = phosphrusintake;
        this.phosphrusunit = phosphrusunit;
        this.seleniumintake = seleniumintake;
        this.seleniumunit = seleniumunit;
        this.fluorineintake = fluorineintake;
        this.fluorineunit = fluorineunit;
        this.cholesterolintake = cholesterolintake;
        this.cholesterolunit = cholesterolunit;
        this.saturatedintake = saturatedintake;
        this.saturatedunit = saturatedunit;
        this.acidregurgitationintake = acidregurgitationintake;
        this.acidregurgitationunit = acidregurgitationunit;
        this.biotinintake = biotinintake;
        this.biotinunit = biotinunit;
        this.cholineintake = cholineintake;
        this.cholineunit = cholineunit;
        this.temp_eatingrecordid = temp_eatingrecordid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getEnergyintake() {
        return energyintake;
    }

    public void setEnergyintake(Double energyintake) {
        this.energyintake = energyintake;
    }

    public String getEnergyunit() {
        return energyunit;
    }

    public void setEnergyunit(String energyunit) {
        this.energyunit = energyunit;
    }

    public Double getMoistureintake() {
        return moistureintake;
    }

    public void setMoistureintake(Double moistureintake) {
        this.moistureintake = moistureintake;
    }

    public String getMoistureunit() {
        return moistureunit;
    }

    public void setMoistureunit(String moistureunit) {
        this.moistureunit = moistureunit;
    }

    public Double getProteinintake() {
        return proteinintake;
    }

    public void setProteinintake(Double proteinintake) {
        this.proteinintake = proteinintake;
    }

    public String getProteinunit() {
        return proteinunit;
    }

    public void setProteinunit(String proteinunit) {
        this.proteinunit = proteinunit;
    }

    public Double getFatintake() {
        return fatintake;
    }

    public void setFatintake(Double fatintake) {
        this.fatintake = fatintake;
    }

    public String getFatunit() {
        return fatunit;
    }

    public void setFatunit(String fatunit) {
        this.fatunit = fatunit;
    }

    public Double getFiberintake() {
        return fiberintake;
    }

    public void setFiberintake(Double fiberintake) {
        this.fiberintake = fiberintake;
    }

    public String getFiberunit() {
        return fiberunit;
    }

    public void setFiberunit(String fiberunit) {
        this.fiberunit = fiberunit;
    }

    public Double getCarbohydrateintake() {
        return carbohydrateintake;
    }

    public void setCarbohydrateintake(Double carbohydrateintake) {
        this.carbohydrateintake = carbohydrateintake;
    }

    public String getCarbohydrateunit() {
        return carbohydrateunit;
    }

    public void setCarbohydrateunit(String carbohydrateunit) {
        this.carbohydrateunit = carbohydrateunit;
    }

    public Double getVitaminaintake() {
        return vitaminaintake;
    }

    public void setVitaminaintake(Double vitaminaintake) {
        this.vitaminaintake = vitaminaintake;
    }

    public String getVitaminaunit() {
        return vitaminaunit;
    }

    public void setVitaminaunit(String vitaminaunit) {
        this.vitaminaunit = vitaminaunit;
    }

    public Double getVitaminb1intake() {
        return vitaminb1intake;
    }

    public void setVitaminb1intake(Double vitaminb1intake) {
        this.vitaminb1intake = vitaminb1intake;
    }

    public String getVitaminb1unit() {
        return vitaminb1unit;
    }

    public void setVitaminb1unit(String vitaminb1unit) {
        this.vitaminb1unit = vitaminb1unit;
    }

    public Double getVitaminb2intake() {
        return vitaminb2intake;
    }

    public void setVitaminb2intake(Double vitaminb2intake) {
        this.vitaminb2intake = vitaminb2intake;
    }

    public String getVitaminb2unit() {
        return vitaminb2unit;
    }

    public void setVitaminb2unit(String vitaminb2unit) {
        this.vitaminb2unit = vitaminb2unit;
    }

    public Double getVitaminb6intake() {
        return vitaminb6intake;
    }

    public void setVitaminb6intake(Double vitaminb6intake) {
        this.vitaminb6intake = vitaminb6intake;
    }

    public String getVitaminb6unit() {
        return vitaminb6unit;
    }

    public void setVitaminb6unit(String vitaminb6unit) {
        this.vitaminb6unit = vitaminb6unit;
    }

    public Double getVitaminb12intake() {
        return vitaminb12intake;
    }

    public void setVitaminb12intake(Double vitaminb12intake) {
        this.vitaminb12intake = vitaminb12intake;
    }

    public String getVitaminb12unit() {
        return vitaminb12unit;
    }

    public void setVitaminb12unit(String vitaminb12unit) {
        this.vitaminb12unit = vitaminb12unit;
    }

    public Double getVitamincintake() {
        return vitamincintake;
    }

    public void setVitamincintake(Double vitamincintake) {
        this.vitamincintake = vitamincintake;
    }

    public String getVitamincunit() {
        return vitamincunit;
    }

    public void setVitamincunit(String vitamincunit) {
        this.vitamincunit = vitamincunit;
    }

    public Double getVitamindintake() {
        return vitamindintake;
    }

    public void setVitamindintake(Double vitamindintake) {
        this.vitamindintake = vitamindintake;
    }

    public String getVitamindunit() {
        return vitamindunit;
    }

    public void setVitamindunit(String vitamindunit) {
        this.vitamindunit = vitamindunit;
    }

    public Double getVitamineintake() {
        return vitamineintake;
    }

    public void setVitamineintake(Double vitamineintake) {
        this.vitamineintake = vitamineintake;
    }

    public String getVitaminunit() {
        return vitaminunit;
    }

    public void setVitaminunit(String vitaminunit) {
        this.vitaminunit = vitaminunit;
    }

    public Double getVitaminkintake() {
        return vitaminkintake;
    }

    public void setVitaminkintake(Double vitaminkintake) {
        this.vitaminkintake = vitaminkintake;
    }

    public String getVitaminkunit() {
        return vitaminkunit;
    }

    public void setVitaminkunit(String vitaminkunit) {
        this.vitaminkunit = vitaminkunit;
    }

    public Double getNicotinicacidintake() {
        return nicotinicacidintake;
    }

    public void setNicotinicacidintake(Double nicotinicacidintake) {
        this.nicotinicacidintake = nicotinicacidintake;
    }

    public String getNicotinicunit() {
        return nicotinicunit;
    }

    public void setNicotinicunit(String nicotinicunit) {
        this.nicotinicunit = nicotinicunit;
    }

    public Double getFolateintake() {
        return folateintake;
    }

    public void setFolateintake(Double folateintake) {
        this.folateintake = folateintake;
    }

    public String getFolateunit() {
        return folateunit;
    }

    public void setFolateunit(String folateunit) {
        this.folateunit = folateunit;
    }

    public Double getSodiumintake() {
        return sodiumintake;
    }

    public void setSodiumintake(Double sodiumintake) {
        this.sodiumintake = sodiumintake;
    }

    public String getSodiumunit() {
        return sodiumunit;
    }

    public void setSodiumunit(String sodiumunit) {
        this.sodiumunit = sodiumunit;
    }

    public Double getCalciumintake() {
        return calciumintake;
    }

    public void setCalciumintake(Double calciumintake) {
        this.calciumintake = calciumintake;
    }

    public String getCalciumunit() {
        return calciumunit;
    }

    public void setCalciumunit(String calciumunit) {
        this.calciumunit = calciumunit;
    }

    public Double getIronintake() {
        return ironintake;
    }

    public void setIronintake(Double ironintake) {
        this.ironintake = ironintake;
    }

    public String getIronunit() {
        return ironunit;
    }

    public void setIronunit(String ironunit) {
        this.ironunit = ironunit;
    }

    public Double getPotassiumintake() {
        return potassiumintake;
    }

    public void setPotassiumintake(Double potassiumintake) {
        this.potassiumintake = potassiumintake;
    }

    public String getPotassiumunit() {
        return potassiumunit;
    }

    public void setPotassiumunit(String potassiumunit) {
        this.potassiumunit = potassiumunit;
    }

    public Double getZincintake() {
        return zincintake;
    }

    public void setZincintake(Double zincintake) {
        this.zincintake = zincintake;
    }

    public String getZincunit() {
        return zincunit;
    }

    public void setZincunit(String zincunit) {
        this.zincunit = zincunit;
    }

    public Double getMagnesiumintake() {
        return magnesiumintake;
    }

    public void setMagnesiumintake(Double magnesiumintake) {
        this.magnesiumintake = magnesiumintake;
    }

    public String getMagnesiumunit() {
        return magnesiumunit;
    }

    public void setMagnesiumunit(String magnesiumunit) {
        this.magnesiumunit = magnesiumunit;
    }

    public Double getCopperintake() {
        return copperintake;
    }

    public void setCopperintake(Double copperintake) {
        this.copperintake = copperintake;
    }

    public String getCopperunit() {
        return copperunit;
    }

    public void setCopperunit(String copperunit) {
        this.copperunit = copperunit;
    }

    public Double getChomuimintake() {
        return chomuimintake;
    }

    public void setChomuimintake(Double chomuimintake) {
        this.chomuimintake = chomuimintake;
    }

    public String getChomuimunit() {
        return chomuimunit;
    }

    public void setChomuimunit(String chomuimunit) {
        this.chomuimunit = chomuimunit;
    }

    public Double getMangaesiumintake() {
        return mangaesiumintake;
    }

    public void setMangaesiumintake(Double mangaesiumintake) {
        this.mangaesiumintake = mangaesiumintake;
    }

    public String getMangaesiumunit() {
        return mangaesiumunit;
    }

    public void setMangaesiumunit(String mangaesiumunit) {
        this.mangaesiumunit = mangaesiumunit;
    }

    public Double getMolybdenumintake() {
        return molybdenumintake;
    }

    public void setMolybdenumintake(Double molybdenumintake) {
        this.molybdenumintake = molybdenumintake;
    }

    public String getMolybdenumunit() {
        return molybdenumunit;
    }

    public void setMolybdenumunit(String molybdenumunit) {
        this.molybdenumunit = molybdenumunit;
    }

    public Double getIodineintake() {
        return iodineintake;
    }

    public void setIodineintake(Double iodineintake) {
        this.iodineintake = iodineintake;
    }

    public String getIodineunit() {
        return iodineunit;
    }

    public void setIodineunit(String iodineunit) {
        this.iodineunit = iodineunit;
    }

    public Double getPhosphrusintake() {
        return phosphrusintake;
    }

    public void setPhosphrusintake(Double phosphrusintake) {
        this.phosphrusintake = phosphrusintake;
    }

    public String getPhosphrusunit() {
        return phosphrusunit;
    }

    public void setPhosphrusunit(String phosphrusunit) {
        this.phosphrusunit = phosphrusunit;
    }

    public Double getSeleniumintake() {
        return seleniumintake;
    }

    public void setSeleniumintake(Double seleniumintake) {
        this.seleniumintake = seleniumintake;
    }

    public String getSeleniumunit() {
        return seleniumunit;
    }

    public void setSeleniumunit(String seleniumunit) {
        this.seleniumunit = seleniumunit;
    }

    public Double getFluorineintake() {
        return fluorineintake;
    }

    public void setFluorineintake(Double fluorineintake) {
        this.fluorineintake = fluorineintake;
    }

    public String getFluorineunit() {
        return fluorineunit;
    }

    public void setFluorineunit(String fluorineunit) {
        this.fluorineunit = fluorineunit;
    }

    public Double getCholesterolintake() {
        return cholesterolintake;
    }

    public void setCholesterolintake(Double cholesterolintake) {
        this.cholesterolintake = cholesterolintake;
    }

    public String getCholesterolunit() {
        return cholesterolunit;
    }

    public void setCholesterolunit(String cholesterolunit) {
        this.cholesterolunit = cholesterolunit;
    }

    public Double getSaturatedintake() {
        return saturatedintake;
    }

    public void setSaturatedintake(Double saturatedintake) {
        this.saturatedintake = saturatedintake;
    }

    public String getSaturatedunit() {
        return saturatedunit;
    }

    public void setSaturatedunit(String saturatedunit) {
        this.saturatedunit = saturatedunit;
    }

    public Double getAcidregurgitationintake() {
        return acidregurgitationintake;
    }

    public void setAcidregurgitationintake(Double acidregurgitationintake) {
        this.acidregurgitationintake = acidregurgitationintake;
    }

    public String getAcidregurgitationunit() {
        return acidregurgitationunit;
    }

    public void setAcidregurgitationunit(String acidregurgitationunit) {
        this.acidregurgitationunit = acidregurgitationunit;
    }

    public Double getBiotinintake() {
        return biotinintake;
    }

    public void setBiotinintake(Double biotinintake) {
        this.biotinintake = biotinintake;
    }

    public String getBiotinunit() {
        return biotinunit;
    }

    public void setBiotinunit(String biotinunit) {
        this.biotinunit = biotinunit;
    }

    public Double getCholineintake() {
        return cholineintake;
    }

    public void setCholineintake(Double cholineintake) {
        this.cholineintake = cholineintake;
    }

    public String getCholineunit() {
        return cholineunit;
    }

    public void setCholineunit(String cholineunit) {
        this.cholineunit = cholineunit;
    }

    public Integer getTemp_eatingrecordid() {
        return temp_eatingrecordid;
    }

    public void setTemp_eatingrecordid(Integer temp_eatingrecordid) {
        this.temp_eatingrecordid = temp_eatingrecordid;
    }

}
