package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HEALTH_SUGGESTIONS_MAPP.
 */
public class HealthSuggestionsMapp {

    private Long id;
    private Integer healthsuggestmappid;
    private String healthsuggcontent;
    private Integer temp_userid;
    private Integer temp_healthsuggestid;
    private String healthsuggestreason;
    private java.util.Date healthsuggesttime;
    private String healthsuggestremarks;

    public HealthSuggestionsMapp() {
    }

    public HealthSuggestionsMapp(Long id) {
        this.id = id;
    }

    public HealthSuggestionsMapp(Long id, Integer healthsuggestmappid, String healthsuggcontent, Integer temp_userid, Integer temp_healthsuggestid, String healthsuggestreason, java.util.Date healthsuggesttime, String healthsuggestremarks) {
        this.id = id;
        this.healthsuggestmappid = healthsuggestmappid;
        this.healthsuggcontent = healthsuggcontent;
        this.temp_userid = temp_userid;
        this.temp_healthsuggestid = temp_healthsuggestid;
        this.healthsuggestreason = healthsuggestreason;
        this.healthsuggesttime = healthsuggesttime;
        this.healthsuggestremarks = healthsuggestremarks;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getHealthsuggestmappid() {
        return healthsuggestmappid;
    }

    public void setHealthsuggestmappid(Integer healthsuggestmappid) {
        this.healthsuggestmappid = healthsuggestmappid;
    }

    public String getHealthsuggcontent() {
        return healthsuggcontent;
    }

    public void setHealthsuggcontent(String healthsuggcontent) {
        this.healthsuggcontent = healthsuggcontent;
    }

    public Integer getTemp_userid() {
        return temp_userid;
    }

    public void setTemp_userid(Integer temp_userid) {
        this.temp_userid = temp_userid;
    }

    public Integer getTemp_healthsuggestid() {
        return temp_healthsuggestid;
    }

    public void setTemp_healthsuggestid(Integer temp_healthsuggestid) {
        this.temp_healthsuggestid = temp_healthsuggestid;
    }

    public String getHealthsuggestreason() {
        return healthsuggestreason;
    }

    public void setHealthsuggestreason(String healthsuggestreason) {
        this.healthsuggestreason = healthsuggestreason;
    }

    public java.util.Date getHealthsuggesttime() {
        return healthsuggesttime;
    }

    public void setHealthsuggesttime(java.util.Date healthsuggesttime) {
        this.healthsuggesttime = healthsuggesttime;
    }

    public String getHealthsuggestremarks() {
        return healthsuggestremarks;
    }

    public void setHealthsuggestremarks(String healthsuggestremarks) {
        this.healthsuggestremarks = healthsuggestremarks;
    }

}
