package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HEALTH_SUGGESTION_COMBILE_SIMPLIFY.
 */
public class HealthSuggestionCombileSimplify {

    private Long id;
    private Integer recommendedconditionsmappid;
    private String temp_healthsuggestlimitedid;
    private String healthsuggestcontent;
    private String healthsuggesttitle;
    private String healthsuggestremarks;
    private String temp_healthsuggtypeid;
    private String healthknowltypeid;
    private Integer healthsuggestflag;
    private Integer healthsuggestcode;
    private String originalpicturepath;
    private String picturename;
    private Boolean isCollected;

    public HealthSuggestionCombileSimplify() {
    }

    public HealthSuggestionCombileSimplify(Long id) {
        this.id = id;
    }

    public HealthSuggestionCombileSimplify(Boolean isCollected) {
        this.isCollected = isCollected;
    }

    public HealthSuggestionCombileSimplify(Long id, Integer recommendedconditionsmappid, String temp_healthsuggestlimitedid, String healthsuggestcontent, String healthsuggesttitle, String healthsuggestremarks, String temp_healthsuggtypeid, String healthknowltypeid, Integer healthsuggestflag, Integer healthsuggestcode, String originalpicturepath, String picturename, Boolean isCollected) {
        this.id = id;
        this.recommendedconditionsmappid = recommendedconditionsmappid;
        this.temp_healthsuggestlimitedid = temp_healthsuggestlimitedid;
        this.healthsuggestcontent = healthsuggestcontent;
        this.healthsuggesttitle = healthsuggesttitle;
        this.healthsuggestremarks = healthsuggestremarks;
        this.temp_healthsuggtypeid = temp_healthsuggtypeid;
        this.healthknowltypeid = healthknowltypeid;
        this.healthsuggestflag = healthsuggestflag;
        this.healthsuggestcode = healthsuggestcode;
        this.originalpicturepath = originalpicturepath;
        this.picturename = picturename;
        this.isCollected = isCollected;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRecommendedconditionsmappid() {
        return recommendedconditionsmappid;
    }

    public void setRecommendedconditionsmappid(Integer recommendedconditionsmappid) {
        this.recommendedconditionsmappid = recommendedconditionsmappid;
    }

    public String getTemp_healthsuggestlimitedid() {
        return temp_healthsuggestlimitedid;
    }

    public void setTemp_healthsuggestlimitedid(String temp_healthsuggestlimitedid) {
        this.temp_healthsuggestlimitedid = temp_healthsuggestlimitedid;
    }

    public String getHealthsuggestcontent() {
        return healthsuggestcontent;
    }

    public void setHealthsuggestcontent(String healthsuggestcontent) {
        this.healthsuggestcontent = healthsuggestcontent;
    }

    public String getHealthsuggesttitle() {
        return healthsuggesttitle;
    }

    public void setHealthsuggesttitle(String healthsuggesttitle) {
        this.healthsuggesttitle = healthsuggesttitle;
    }

    public String getHealthsuggestremarks() {
        return healthsuggestremarks;
    }

    public void setHealthsuggestremarks(String healthsuggestremarks) {
        this.healthsuggestremarks = healthsuggestremarks;
    }

    public String getTemp_healthsuggtypeid() {
        return temp_healthsuggtypeid;
    }

    public void setTemp_healthsuggtypeid(String temp_healthsuggtypeid) {
        this.temp_healthsuggtypeid = temp_healthsuggtypeid;
    }

    public String getHealthknowltypeid() {
        return healthknowltypeid;
    }

    public void setHealthknowltypeid(String healthknowltypeid) {
        this.healthknowltypeid = healthknowltypeid;
    }

    public Integer getHealthsuggestflag() {
        return healthsuggestflag;
    }

    public void setHealthsuggestflag(Integer healthsuggestflag) {
        this.healthsuggestflag = healthsuggestflag;
    }

    public Integer getHealthsuggestcode() {
        return healthsuggestcode;
    }

    public void setHealthsuggestcode(Integer healthsuggestcode) {
        this.healthsuggestcode = healthsuggestcode;
    }

    public String getOriginalpicturepath() {
        return originalpicturepath;
    }

    public void setOriginalpicturepath(String originalpicturepath) {
        this.originalpicturepath = originalpicturepath;
    }

    public String getPicturename() {
        return picturename;
    }

    public void setPicturename(String picturename) {
        this.picturename = picturename;
    }

    public Boolean getIsCollected() {
        return isCollected;
    }

    public void setIsCollected(Boolean isCollected) {
        this.isCollected = isCollected;
    }

}
