package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HEALTH_SUGG_TYPE.
 */
public class HealthSuggType {

    private Long id;
    private Integer healthsuggtypeid;
    private String healthsuggtypename;
    private Integer healthsuggtypecode;
    private String suggclassifyexpla;
    private String healthsuggtyperemarks;

    public HealthSuggType() {
    }

    public HealthSuggType(Long id) {
        this.id = id;
    }

    public HealthSuggType(Long id, Integer healthsuggtypeid, String healthsuggtypename, Integer healthsuggtypecode, String suggclassifyexpla, String healthsuggtyperemarks) {
        this.id = id;
        this.healthsuggtypeid = healthsuggtypeid;
        this.healthsuggtypename = healthsuggtypename;
        this.healthsuggtypecode = healthsuggtypecode;
        this.suggclassifyexpla = suggclassifyexpla;
        this.healthsuggtyperemarks = healthsuggtyperemarks;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getHealthsuggtypeid() {
        return healthsuggtypeid;
    }

    public void setHealthsuggtypeid(Integer healthsuggtypeid) {
        this.healthsuggtypeid = healthsuggtypeid;
    }

    public String getHealthsuggtypename() {
        return healthsuggtypename;
    }

    public void setHealthsuggtypename(String healthsuggtypename) {
        this.healthsuggtypename = healthsuggtypename;
    }

    public Integer getHealthsuggtypecode() {
        return healthsuggtypecode;
    }

    public void setHealthsuggtypecode(Integer healthsuggtypecode) {
        this.healthsuggtypecode = healthsuggtypecode;
    }

    public String getSuggclassifyexpla() {
        return suggclassifyexpla;
    }

    public void setSuggclassifyexpla(String suggclassifyexpla) {
        this.suggclassifyexpla = suggclassifyexpla;
    }

    public String getHealthsuggtyperemarks() {
        return healthsuggtyperemarks;
    }

    public void setHealthsuggtyperemarks(String healthsuggtyperemarks) {
        this.healthsuggtyperemarks = healthsuggtyperemarks;
    }

}
