package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HEALTH_SUGGESTIONS.
 */
//改用Recommendedconditionsmapp来做健康建议的获取
public class HealthSuggestions {

    private Long id;
    private Integer healthsuggestid;
    private String healthsuggestcontent;
    private String healthsuggesttitle;
    private String healthsuggestremarks;
    private String temp_healthsuggtypeid;
    private Integer healthsuggestflag;
    private Integer healthsuggestcode;
    private PictureList temp_picturelocationid;

    public HealthSuggestions() {
    }

    public HealthSuggestions(Long id) {
        this.id = id;
    }

    public HealthSuggestions(Long id, Integer healthsuggestid, String healthsuggestcontent, String healthsuggesttitle, String healthsuggestremarks, String temp_healthsuggtypeid, Integer healthsuggestflag, Integer healthsuggestcode) {
        this.id = id;
        this.healthsuggestid = healthsuggestid;
        this.healthsuggestcontent = healthsuggestcontent;
        this.healthsuggesttitle = healthsuggesttitle;
        this.healthsuggestremarks = healthsuggestremarks;
        this.temp_healthsuggtypeid = temp_healthsuggtypeid;
        this.healthsuggestflag = healthsuggestflag;
        this.healthsuggestcode = healthsuggestcode;
    }
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getHealthsuggestid() {
        return healthsuggestid;
    }

    public void setHealthsuggestid(Integer healthsuggestid) {
        this.healthsuggestid = healthsuggestid;
    }

    public String getHealthsuggestcontent() {
        return healthsuggestcontent;
    }

    public void setHealthsuggestcontent(String healthsuggestcontent) {
        this.healthsuggestcontent = healthsuggestcontent;
    }

    public String getHealthsuggesttitle() {
        return healthsuggesttitle;
    }

    public void setHealthsuggesttitle(String healthsuggesttitle) {
        this.healthsuggesttitle = healthsuggesttitle;
    }

    public String getHealthsuggestremarks() {
        return healthsuggestremarks;
    }

    public void setHealthsuggestremarks(String healthsuggestremarks) {
        this.healthsuggestremarks = healthsuggestremarks;
    }

    public String getTemp_healthsuggtypeid() {
        return temp_healthsuggtypeid;
    }

    public void setTemp_healthsuggtypeid(String temp_healthsuggtypeid) {
        this.temp_healthsuggtypeid = temp_healthsuggtypeid;
    }

    public Integer getHealthsuggestflag() {
        return healthsuggestflag;
    }

    public void setHealthsuggestflag(Integer healthsuggestflag) {
        this.healthsuggestflag = healthsuggestflag;
    }

    public Integer getHealthsuggestcode() {
        return healthsuggestcode;
    }

    public void setHealthsuggestcode(Integer healthsuggestcode) {
        this.healthsuggestcode = healthsuggestcode;
    }

    public PictureList getTemp_picturelocationid() {
        return temp_picturelocationid;
    }

    public void setTemp_picturelocationid(PictureList temp_picturelocationid) {
        this.temp_picturelocationid = temp_picturelocationid;
    }
}
