package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IDENTIFY_CHOICES.
 */
public class IdentifyChoices {

    private Long id;
    private Integer identifychoiceid;
    private Integer identifychoicevalue;
    private String scriptdescribe;

    public IdentifyChoices() {
    }

    public IdentifyChoices(Long id) {
        this.id = id;
    }

    public IdentifyChoices(Long id, Integer identifychoiceid, Integer identifychoicevalue, String scriptdescribe) {
        this.id = id;
        this.identifychoiceid = identifychoiceid;
        this.identifychoicevalue = identifychoicevalue;
        this.scriptdescribe = scriptdescribe;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdentifychoiceid() {
        return identifychoiceid;
    }

    public void setIdentifychoiceid(Integer identifychoiceid) {
        this.identifychoiceid = identifychoiceid;
    }

    public Integer getIdentifychoicevalue() {
        return identifychoicevalue;
    }

    public void setIdentifychoicevalue(Integer identifychoicevalue) {
        this.identifychoicevalue = identifychoicevalue;
    }

    public String getScriptdescribe() {
        return scriptdescribe;
    }

    public void setScriptdescribe(String scriptdescribe) {
        this.scriptdescribe = scriptdescribe;
    }

}
