package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Recommendedconditionsmapp.
 */
//结合了三张表，用来获取特定类型用户的健康建议
public class Recommendedconditionsmapp {

    private Long id;
    private Integer recommendedconditionsmappid;
    private String temp_healthsuggestlimitedid;
    private HealthSuggestions temp_healthsuggestid;
    private String recommendmappremarks;

    public Recommendedconditionsmapp() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRecommendedconditionsmappid() {
        return recommendedconditionsmappid;
    }

    public void setRecommendedconditionsmappid(Integer recommendedconditionsmappid) {
        this.recommendedconditionsmappid = recommendedconditionsmappid;
    }

    public String getTemp_healthsuggestlimitedid() {
        return temp_healthsuggestlimitedid;
    }

    public void setTemp_healthsuggestlimitedid(String temp_healthsuggestlimitedid) {
        this.temp_healthsuggestlimitedid = temp_healthsuggestlimitedid;
    }

    public HealthSuggestions getTemp_healthsuggestid() {
        return temp_healthsuggestid;
    }

    public void setTemp_healthsuggestid(HealthSuggestions temp_healthsuggestid) {
        this.temp_healthsuggestid = temp_healthsuggestid;
    }

    public String getRecommendmappremarks() {
        return recommendmappremarks;
    }

    public void setRecommendmappremarks(String recommendmappremarks) {
        this.recommendmappremarks = recommendmappremarks;
    }


}
