package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SLEEP_PREFER_RECORDS.
 */
public class SleepPreferRecords {

    private Long id;
    private Integer sleeppreferid;
    private java.util.Date prefersleepbeginat;
    private java.util.Date prefersleepoverat;
    private Integer temp_locationinfoid;
    private Integer temp_userid;

    public SleepPreferRecords() {
    }

    public SleepPreferRecords(Long id) {
        this.id = id;
    }

    public SleepPreferRecords(Long id, Integer sleeppreferid, java.util.Date prefersleepbeginat, java.util.Date prefersleepoverat, Integer temp_locationinfoid, Integer temp_userid) {
        this.id = id;
        this.sleeppreferid = sleeppreferid;
        this.prefersleepbeginat = prefersleepbeginat;
        this.prefersleepoverat = prefersleepoverat;
        this.temp_locationinfoid = temp_locationinfoid;
        this.temp_userid = temp_userid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSleeppreferid() {
        return sleeppreferid;
    }

    public void setSleeppreferid(Integer sleeppreferid) {
        this.sleeppreferid = sleeppreferid;
    }

    public java.util.Date getPrefersleepbeginat() {
        return prefersleepbeginat;
    }

    public void setPrefersleepbeginat(java.util.Date prefersleepbeginat) {
        this.prefersleepbeginat = prefersleepbeginat;
    }

    public java.util.Date getPrefersleepoverat() {
        return prefersleepoverat;
    }

    public void setPrefersleepoverat(java.util.Date prefersleepoverat) {
        this.prefersleepoverat = prefersleepoverat;
    }

    public Integer getTemp_locationinfoid() {
        return temp_locationinfoid;
    }

    public void setTemp_locationinfoid(Integer temp_locationinfoid) {
        this.temp_locationinfoid = temp_locationinfoid;
    }

    public Integer getTemp_userid() {
        return temp_userid;
    }

    public void setTemp_userid(Integer temp_userid) {
        this.temp_userid = temp_userid;
    }

}
