package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SLEEP_INFO_RECORDS.
 */
public class SleepInfoRecords {

    private Long id;
    private Integer sleeprecordid;
    private Double airhumidity;
    private Double ambienttemperature;
    private Double ambientnoise;
    private String sleepbegin;
    private String sleepover;
    private Double deepsleeptime;
    private Double shallowsleeptime;
    private String sleepremarks;
    private String sleeprecorduptime;
    private String temp_userid;
    private Integer temp_locationinfoid;
    private Integer waketimes;
    private Integer temp_intelligentdeviceid;
    private Integer intelligentdevicecode;
    private Integer sleepuploadflag;
    private String awaketime;

    public SleepInfoRecords() {
    }

    public SleepInfoRecords(Long id) {
        this.id = id;
    }

    public SleepInfoRecords(Long id, Integer sleeprecordid, Double airhumidity, Double ambienttemperature, Double ambientnoise, String sleepbegin, String sleepover, Double deepsleeptime, Double shallowsleeptime, String sleepremarks, String sleeprecorduptime, String temp_userid, Integer temp_locationinfoid, Integer waketimes, Integer temp_intelligentdeviceid, Integer intelligentdevicecode,Integer sleepuploadflag,String awaketime) {
        this.id = id;
        this.sleeprecordid = sleeprecordid;
        this.airhumidity = airhumidity;
        this.ambienttemperature = ambienttemperature;
        this.ambientnoise = ambientnoise;
        this.sleepbegin = sleepbegin;
        this.sleepover = sleepover;
        this.deepsleeptime = deepsleeptime;
        this.shallowsleeptime = shallowsleeptime;
        this.sleepremarks = sleepremarks;
        this.sleeprecorduptime = sleeprecorduptime;
        this.temp_userid = temp_userid;
        this.temp_locationinfoid = temp_locationinfoid;
        this.waketimes = waketimes;
        this.temp_intelligentdeviceid = temp_intelligentdeviceid;
        this.intelligentdevicecode = intelligentdevicecode;
        this.sleepuploadflag = sleepuploadflag;
        this.awaketime = awaketime;
    }
    public SleepInfoRecords( String sleepbegin, String sleepover, String sleepremarks, String sleeprecorduptime, String temp_userid) {

        this.sleepbegin = sleepbegin;
        this.sleepover = sleepover;
        this.sleepremarks = sleepremarks;
        this.sleeprecorduptime = sleeprecorduptime;
        this.temp_userid = temp_userid;
    }



    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSleeprecordid() {
        return sleeprecordid;
    }

    public void setSleeprecordid(Integer sleeprecordid) {
        this.sleeprecordid = sleeprecordid;
    }

    public Double getAirhumidity() {
        return airhumidity;
    }

    public void setAirhumidity(Double airhumidity) {
        this.airhumidity = airhumidity;
    }

    public Double getAmbienttemperature() {
        return ambienttemperature;
    }

    public void setAmbienttemperature(Double ambienttemperature) {
        this.ambienttemperature = ambienttemperature;
    }

    public Double getAmbientnoise() {
        return ambientnoise;
    }

    public void setAmbientnoise(Double ambientnoise) {
        this.ambientnoise = ambientnoise;
    }

    public String getSleepbegin() {
        return sleepbegin;
    }

    public void setSleepbegin(String sleepbegin) {
        this.sleepbegin = sleepbegin;
    }

    public String getSleepover() {
        return sleepover;
    }

    public void setSleepover(String sleepover) {
        this.sleepover = sleepover;
    }

    public Double getDeepsleeptime() {
        return deepsleeptime;
    }

    public void setDeepsleeptime(Double deepsleeptime) {
        this.deepsleeptime = deepsleeptime;
    }

    public Double getShallowsleeptime() {
        return shallowsleeptime;
    }

    public void setShallowsleeptime(Double shallowsleeptime) {
        this.shallowsleeptime = shallowsleeptime;
    }

    public String getSleepremarks() {
        return sleepremarks;
    }

    public void setSleepremarks(String sleepremarks) {
        this.sleepremarks = sleepremarks;
    }

    public String getSleeprecorduptime() {
        return sleeprecorduptime;
    }

    public void setSleeprecorduptime(String sleeprecorduptime) {
        this.sleeprecorduptime = sleeprecorduptime;
    }

    public String getTemp_userid() {
        return temp_userid;
    }

    public void setTemp_userid(String temp_userid) {
        this.temp_userid = temp_userid;
    }

    public Integer getTemp_locationinfoid() {
        return temp_locationinfoid;
    }

    public void setTemp_locationinfoid(Integer temp_locationinfoid) {
        this.temp_locationinfoid = temp_locationinfoid;
    }

    public Integer getWaketimes() {
        return waketimes;
    }

    public void setWaketimes(Integer waketimes) {
        this.waketimes = waketimes;
    }

    public Integer getTemp_intelligentdeviceid() {
        return temp_intelligentdeviceid;
    }

    public void setTemp_intelligentdeviceid(Integer temp_intelligentdeviceid) {
        this.temp_intelligentdeviceid = temp_intelligentdeviceid;
    }

    public Integer getIntelligentdevicecode() {
        return intelligentdevicecode;
    }

    public void setIntelligentdevicecode(Integer intelligentdevicecode) {
        this.intelligentdevicecode = intelligentdevicecode;
    }

    public Integer getSleepuploadflag() {
        return sleepuploadflag;
    }

    public void setSleepuploadflag(Integer sleepuploadflag) {
        this.sleepuploadflag = sleepuploadflag;
    }

    public String getAwaketime() {
        return awaketime;
    }

    public void setAwaketime(String awaketime) {
        this.awaketime = awaketime;
    }
}
