package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_SLEEP_FEATURE.
 */
public class UserSleepFeature {

    private Long id;
    private Integer sleepfeatureid;
    private Double airhumidity;
    private Double ambienttemperature;
    private Double ambientnoise;
    private String bedtimehabits;
    private String goodbedtimehabits;
    private String siestahabit;
    private Double averagesleeptime;
    private String sleephabitdetemination;
    private String sleepindex;
    private String sleephabitanalysis;
    private Integer temp_locationinfoid;

    public UserSleepFeature() {
    }

    public UserSleepFeature(Long id) {
        this.id = id;
    }

    public UserSleepFeature(Long id, Integer sleepfeatureid, Double airhumidity, Double ambienttemperature, Double ambientnoise, String bedtimehabits, String goodbedtimehabits, String siestahabit, Double averagesleeptime, String sleephabitdetemination, String sleepindex, String sleephabitanalysis, Integer temp_locationinfoid) {
        this.id = id;
        this.sleepfeatureid = sleepfeatureid;
        this.airhumidity = airhumidity;
        this.ambienttemperature = ambienttemperature;
        this.ambientnoise = ambientnoise;
        this.bedtimehabits = bedtimehabits;
        this.goodbedtimehabits = goodbedtimehabits;
        this.siestahabit = siestahabit;
        this.averagesleeptime = averagesleeptime;
        this.sleephabitdetemination = sleephabitdetemination;
        this.sleepindex = sleepindex;
        this.sleephabitanalysis = sleephabitanalysis;
        this.temp_locationinfoid = temp_locationinfoid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSleepfeatureid() {
        return sleepfeatureid;
    }

    public void setSleepfeatureid(Integer sleepfeatureid) {
        this.sleepfeatureid = sleepfeatureid;
    }

    public Double getAirhumidity() {
        return airhumidity;
    }

    public void setAirhumidity(Double airhumidity) {
        this.airhumidity = airhumidity;
    }

    public Double getAmbienttemperature() {
        return ambienttemperature;
    }

    public void setAmbienttemperature(Double ambienttemperature) {
        this.ambienttemperature = ambienttemperature;
    }

    public Double getAmbientnoise() {
        return ambientnoise;
    }

    public void setAmbientnoise(Double ambientnoise) {
        this.ambientnoise = ambientnoise;
    }

    public String getBedtimehabits() {
        return bedtimehabits;
    }

    public void setBedtimehabits(String bedtimehabits) {
        this.bedtimehabits = bedtimehabits;
    }

    public String getGoodbedtimehabits() {
        return goodbedtimehabits;
    }

    public void setGoodbedtimehabits(String goodbedtimehabits) {
        this.goodbedtimehabits = goodbedtimehabits;
    }

    public String getSiestahabit() {
        return siestahabit;
    }

    public void setSiestahabit(String siestahabit) {
        this.siestahabit = siestahabit;
    }

    public Double getAveragesleeptime() {
        return averagesleeptime;
    }

    public void setAveragesleeptime(Double averagesleeptime) {
        this.averagesleeptime = averagesleeptime;
    }

    public String getSleephabitdetemination() {
        return sleephabitdetemination;
    }

    public void setSleephabitdetemination(String sleephabitdetemination) {
        this.sleephabitdetemination = sleephabitdetemination;
    }

    public String getSleepindex() {
        return sleepindex;
    }

    public void setSleepindex(String sleepindex) {
        this.sleepindex = sleepindex;
    }

    public String getSleephabitanalysis() {
        return sleephabitanalysis;
    }

    public void setSleephabitanalysis(String sleephabitanalysis) {
        this.sleephabitanalysis = sleephabitanalysis;
    }

    public Integer getTemp_locationinfoid() {
        return temp_locationinfoid;
    }

    public void setTemp_locationinfoid(Integer temp_locationinfoid) {
        this.temp_locationinfoid = temp_locationinfoid;
    }

}
