package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_HEALTHKNOWAGE.
 */
public class UserHealthknowage {

    private Long id;
    private Integer userknowledgemappid;
    private Integer temp_picturelistid;
    private java.util.Date healthknowledgetime;
    private Integer userid;
    private String username;
    private Integer healthknowltypeid;
    private String healthknowltypename;
    private String healthknowledgetitle;
    private String healthknowledgecontent;
    private Integer healthknowledgecode;
    private Boolean isCollected;

    public UserHealthknowage() {
    }

    public UserHealthknowage(Long id) {
        this.id = id;
    }

    public UserHealthknowage(Long id, Integer userknowledgemappid, Integer temp_picturelistid, java.util.Date healthknowledgetime, Integer userid, String username, Integer healthknowltypeid, String healthknowltypename, String healthknowledgetitle, String healthknowledgecontent, Integer healthknowledgecode, Boolean isCollected) {
        this.id = id;
        this.userknowledgemappid = userknowledgemappid;
        this.temp_picturelistid = temp_picturelistid;
        this.healthknowledgetime = healthknowledgetime;
        this.userid = userid;
        this.username = username;
        this.healthknowltypeid = healthknowltypeid;
        this.healthknowltypename = healthknowltypename;
        this.healthknowledgetitle = healthknowledgetitle;
        this.healthknowledgecontent = healthknowledgecontent;
        this.healthknowledgecode = healthknowledgecode;
        this.isCollected = isCollected;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserknowledgemappid() {
        return userknowledgemappid;
    }

    public void setUserknowledgemappid(Integer userknowledgemappid) {
        this.userknowledgemappid = userknowledgemappid;
    }

    public Integer getTemp_picturelistid() {
        return temp_picturelistid;
    }

    public void setTemp_picturelistid(Integer temp_picturelistid) {
        this.temp_picturelistid = temp_picturelistid;
    }

    public java.util.Date getHealthknowledgetime() {
        return healthknowledgetime;
    }

    public void setHealthknowledgetime(java.util.Date healthknowledgetime) {
        this.healthknowledgetime = healthknowledgetime;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Integer getHealthknowltypeid() {
        return healthknowltypeid;
    }

    public void setHealthknowltypeid(Integer healthknowltypeid) {
        this.healthknowltypeid = healthknowltypeid;
    }

    public String getHealthknowltypename() {
        return healthknowltypename;
    }

    public void setHealthknowltypename(String healthknowltypename) {
        this.healthknowltypename = healthknowltypename;
    }

    public String getHealthknowledgetitle() {
        return healthknowledgetitle;
    }

    public void setHealthknowledgetitle(String healthknowledgetitle) {
        this.healthknowledgetitle = healthknowledgetitle;
    }

    public String getHealthknowledgecontent() {
        return healthknowledgecontent;
    }

    public void setHealthknowledgecontent(String healthknowledgecontent) {
        this.healthknowledgecontent = healthknowledgecontent;
    }

    public Integer getHealthknowledgecode() {
        return healthknowledgecode;
    }

    public void setHealthknowledgecode(Integer healthknowledgecode) {
        this.healthknowledgecode = healthknowledgecode;
    }

    public Boolean getIsCollected() {
        return isCollected;
    }

    public void setIsCollected(Boolean isCollected) {
        this.isCollected = isCollected;
    }

}
