package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_KNOWLEDGE_MAPP.
 */
public class UserKnowledgeMapp {

    private Long id;
    private Integer userknowledgemappid;
    private Integer temp_userid;
    private String healthknowledgecontent;
    private Integer temp_healthknowledgeid;
    private String healthknowledgereason;
    private java.util.Date healthknowledgetime;
    private String healthknowledgeremarks;

    public UserKnowledgeMapp() {
    }

    public UserKnowledgeMapp(Long id) {
        this.id = id;
    }

    public UserKnowledgeMapp(Long id, Integer userknowledgemappid, Integer temp_userid, String healthknowledgecontent, Integer temp_healthknowledgeid, String healthknowledgereason, java.util.Date healthknowledgetime, String healthknowledgeremarks) {
        this.id = id;
        this.userknowledgemappid = userknowledgemappid;
        this.temp_userid = temp_userid;
        this.healthknowledgecontent = healthknowledgecontent;
        this.temp_healthknowledgeid = temp_healthknowledgeid;
        this.healthknowledgereason = healthknowledgereason;
        this.healthknowledgetime = healthknowledgetime;
        this.healthknowledgeremarks = healthknowledgeremarks;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserknowledgemappid() {
        return userknowledgemappid;
    }

    public void setUserknowledgemappid(Integer userknowledgemappid) {
        this.userknowledgemappid = userknowledgemappid;
    }

    public Integer getTemp_userid() {
        return temp_userid;
    }

    public void setTemp_userid(Integer temp_userid) {
        this.temp_userid = temp_userid;
    }

    public String getHealthknowledgecontent() {
        return healthknowledgecontent;
    }

    public void setHealthknowledgecontent(String healthknowledgecontent) {
        this.healthknowledgecontent = healthknowledgecontent;
    }

    public Integer getTemp_healthknowledgeid() {
        return temp_healthknowledgeid;
    }

    public void setTemp_healthknowledgeid(Integer temp_healthknowledgeid) {
        this.temp_healthknowledgeid = temp_healthknowledgeid;
    }

    public String getHealthknowledgereason() {
        return healthknowledgereason;
    }

    public void setHealthknowledgereason(String healthknowledgereason) {
        this.healthknowledgereason = healthknowledgereason;
    }

    public java.util.Date getHealthknowledgetime() {
        return healthknowledgetime;
    }

    public void setHealthknowledgetime(java.util.Date healthknowledgetime) {
        this.healthknowledgetime = healthknowledgetime;
    }

    public String getHealthknowledgeremarks() {
        return healthknowledgeremarks;
    }

    public void setHealthknowledgeremarks(String healthknowledgeremarks) {
        this.healthknowledgeremarks = healthknowledgeremarks;
    }

}
