package com.njucm.cmdh.app.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_ANSWER_RECORDS.
 */
public class UserAnswerRecords {

    private Long id;
    private Integer issuescoremappid;
    private Integer temp_identifyissueid;
    private Integer temp_identifyscoreid;
    private Integer temp_userid;

    public UserAnswerRecords() {
    }

    public UserAnswerRecords(Long id) {
        this.id = id;
    }

    public UserAnswerRecords(Long id, Integer issuescoremappid, Integer temp_identifyissueid, Integer temp_identifyscoreid, Integer temp_userid) {
        this.id = id;
        this.issuescoremappid = issuescoremappid;
        this.temp_identifyissueid = temp_identifyissueid;
        this.temp_identifyscoreid = temp_identifyscoreid;
        this.temp_userid = temp_userid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIssuescoremappid() {
        return issuescoremappid;
    }

    public void setIssuescoremappid(Integer issuescoremappid) {
        this.issuescoremappid = issuescoremappid;
    }

    public Integer getTemp_identifyissueid() {
        return temp_identifyissueid;
    }

    public void setTemp_identifyissueid(Integer temp_identifyissueid) {
        this.temp_identifyissueid = temp_identifyissueid;
    }

    public Integer getTemp_identifyscoreid() {
        return temp_identifyscoreid;
    }

    public void setTemp_identifyscoreid(Integer temp_identifyscoreid) {
        this.temp_identifyscoreid = temp_identifyscoreid;
    }

    public Integer getTemp_userid() {
        return temp_userid;
    }

    public void setTemp_userid(Integer temp_userid) {
        this.temp_userid = temp_userid;
    }

}
